### PR TITLE
feat: better error, const constructor and various impl(s)

### PR DESCRIPTION
**Pull request by carlocorradini**
This PR adds the following features:
- `DurationString` is a tuple `struct` (single) where `.0` is `std::time::Duration` (this offers a number of advantages, such as "automatic derive")
- `const` constructor
- Custom `Error` via [thiserror](https://github.com/dtolnay/thiserror)
- Various "automatic" `impl` (same as `std::time::Duration`):
    - `Eq`
    - `PartialOrd`
    - `Ord`
    - `Hash`
    - `Default`
- Custom `impl`:
    - `Deref`
    - `DerefMut`
    - `Borrow`
    - `BorrowMut`

Let me know what you think 🤯🥳

### CODE REVIEW

**Comment by RonniSkansing** [comment]
Very nice, only comment would be that I would like to keep the lib dependency free (atleast the only deps are dev deps.)

**Comment by carlocorradini** [comment]
Fixed:
- Removed `thiserror` dependency
- Better `.gitignore` and added `.gitattributes`
- Automatic `LICENSE` year update via `license.yaml` workflow
- Added VSCode files
- Added Dependabot
- Added CODEOWNERS
- Added Editorconfig file
- Fixed some typos and better `README.md` file

**Comment by carlocorradini** [comment]
@RonniSkansing Any update? 🥳🤯

**Review by RonniSkansing — APPROVED** [review]

**Comment by RonniSkansing** [comment]
Thanks!

Do you want to add yourself to authors? https://github.com/RonniSkansing/duration-string/blob/master/Cargo.toml

**Pull request merged**
